version: "3.8"

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pokemon
    restart: always
    ports:
      - 5432:5432
    networks:
      - network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  dbdata:
